### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/xrsocial-client#183]
PURPLE!

1. Loading screens are working and properly displaying for the right amount of time.

2. Loading progress bar with rough heuristic from files downloading.

3. Randomize from small collection of designed loading screens, which are mostly CSS.

**Comment by mohrtw** [comment]
Add the progress bar to scene-container.
Get the children of a-assets, add a 'load' event listener for each child.
Fill the progress bar based on the percentage of assets loaded.

**Comment by dmitrizagidulin** [comment]
Implemented, closing.
