### ISSUE TITLE
360 player doesn't render EAC properly when link hit directly

### ISSUE THREAD

**Issue by barankyle** [xr3ngine/xrsocial-client#346]
EAC videos all seem to be rendered fine when accessed through the explore page via the grid and then hitting watch on the info card. If I try to hit a link to play a video directly, however, it seems to be ignoring the video format and trying to play it as equirectangular - I see the distinctive horizontal split of it not trying to map.

For example, if you go directly to 

https://dev.kaixr.world/video360?manifest=https://s3.amazonaws.com/kaixr-static-resources/public/youtube/wwH3fygSNVU/video/manifest.mpd&title=Explore%20Penguins%20&runtime=3:07&credit=Nat%20Geo&rating=All&categories=Health%20&%20Science,Playground&videoformat=eac

you should see it not render it as an EAC, even though the videoformat is set correctly in the link.

**Comment by campbellgoe** [comment]
As a workaround for now, it should work by specifying 'format' instead of 'videoformat'.

**Comment by mohrtw** [comment]
Resolved by #362
