### ISSUE TITLE
Load A-Frame scene only once and dynamically change contents

### ISSUE THREAD

**Issue by mohrtw** [xr3ngine/xrsocial-client#53]
Currently, we are navigating to new pages and have to load a new scene and reload all of the assets.

**Comment by campbellgoe** [comment]
#14 I'm working on this issue.

**Comment by campbellgoe** [comment]
We can use next/link and next/router to dynamically route between pages. We need to make sure it doesn't attempt to reinitialize aframe and components such as 'player' on each navigation, but only the initial page load. When loading directly to some page, it needs to always initialize aframe, the player, assets, the scene etc.
My thoughts are to keep the initialization code at the root of each page, but pass in page specific scene components & entities as children which are rendered inside the root (see /components/xr/scene/scene.tsx - we pass children into here which are specific for the route).
This means react can do its diffing algorithm and keep the root react components untouched, whilst updating the children specific for the route, when navigating.

**Comment by campbellgoe** [comment]
This is solved in xrchat/xrchat-client-portal-demo. This led to issue #85 - we want to integrate this solution into xrchat-client. This will involve taking code / functionality that was removed in the portal demo version, and writing it in a way that will keep routing working, such that A-Frame only loads once (on directly navigating to an aframe page for the first time).

**Comment by mohrtw** [comment]
Resolved by #279
